psw = "123456"
admin_user = ("admin@gmail.com", psw)
ordinary_user_1 = ("user_1@gmail.com", psw)
ordinary_user_2 = ("user_2@gmail.com", psw)
not_user = ("no_email", "no_psw")


movies_data = (
    {
        "title": "Pulp Fiction",
        "year": 1994,
        "director_id": 1,
        "rate": 8.9,
        "user_id": 1,
    },
    {
        "title": "Django Unchained",
        "year": 2012,
        "director_id": 1,
        "rate": 8.4,
        "user_id": 1,
    },
    {
        "title": "Parasite",
        "year": 2019,
        "director_id": 2,
        "rate": 8.5,
        "user_id": 1,
    },
    {
        "title": "Memories of Murder",
        "year": 2003,
        "director_id": 2,
        "rate": 8.1,
        "user_id": 1,
    },
    {
        "title": "Birdman or (The Unexpected Virtue of Ignorance)",
        "year": 2014,
        "director_id": 3,
        "rate": 7.7,
        "user_id": 1,
    },
    {
        "title": "Bardo, False Chronicle of a Handful of Truths",
        "year": 2022,
        "director_id": 3,
        "rate": 6.7,
        "user_id": 1,
    },
    {
        "title": "Eyes Wide Shut",
        "year": 1999,
        "director_id": 4,
        "rate": 7.5,
        "user_id": 1,
    },
    {
        "title": "Full Metal Jacket",
        "year": 1987,
        "director_id": 4,
        "rate": 8.4,
        "user_id": 1,
    },
    {
        "title": "The Shining",
        "year": 1980,
        "director_id": 4,
        "rate": 8.4,
        "user_id": 1,
    },
    {
        "title": "Fargo",
        "year": 1996,
        "director_id": 5,
        "rate": 8.1,
        "user_id": 1,
    },
    {
        "title": "No Country for Old Men",
        "year": 2007,
        "director_id": 5,
        "rate": 8.2,
        "user_id": 1,
    },
    {
        "title": "The Big Lebowski",
        "year": 1998,
        "director_id": 5,
        "rate": 8.1,
        "user_id": 1,
    },
    {
        "title": "The Banshees of Inisherin",
        "year": 2022,
        "director_id": 6,
        "rate": 7.7,
        "user_id": 1,
    },
    {
        "title": "Three Billboards Outside Ebbing, Missouri",
        "year": 2022,
        "director_id": 6,
        "rate": 7.7,
        "user_id": 1,
    },
    {
        "title": "Loro",
        "year": 2018,
        "director_id": 7,
        "rate": 6.7,
        "user_id": 1,
    },
    {
        "title": "Youth",
        "year": 2015,
        "director_id": 7,
        "rate": 7.3,
        "user_id": 1,
    },
)

movies_genres_data = (
    {"genre_id": 6, "movie_id": 1},
    {"genre_id": 5, "movie_id": 1},
    {"genre_id": 8, "movie_id": 2},
    {"genre_id": 26, "movie_id": 2},
    {"genre_id": 8, "movie_id": 3},
    {"genre_id": 24, "movie_id": 3},
    {"genre_id": 8, "movie_id": 4},
    {"genre_id": 6, "movie_id": 4},
    {"genre_id": 17, "movie_id": 4},
    {"genre_id": 8, "movie_id": 5},
    {"genre_id": 5, "movie_id": 5},
    {"genre_id": 5, "movie_id": 6},
    {"genre_id": 8, "movie_id": 6},
    {"genre_id": 8, "movie_id": 7},
    {"genre_id": 17, "movie_id": 7},
    {"genre_id": 24, "movie_id": 7},
    {"genre_id": 8, "movie_id": 8},
    {"genre_id": 25, "movie_id": 8},
    {"genre_id": 8, "movie_id": 9},
    {"genre_id": 14, "movie_id": 9},
    {"genre_id": 6, "movie_id": 10},
    {"genre_id": 8, "movie_id": 10},
    {"genre_id": 24, "movie_id": 10},
    {"genre_id": 6, "movie_id": 11},
    {"genre_id": 8, "movie_id": 11},
    {"genre_id": 24, "movie_id": 11},
    {"genre_id": 6, "movie_id": 12},
    {"genre_id": 5, "movie_id": 12},
    {"genre_id": 8, "movie_id": 13},
    {"genre_id": 5, "movie_id": 13},
    {"genre_id": 8, "movie_id": 14},
    {"genre_id": 5, "movie_id": 14},
    {"genre_id": 6, "movie_id": 14},
    {"genre_id": 8, "movie_id": 15},
    {"genre_id": 4, "movie_id": 15},
    {"genre_id": 5, "movie_id": 16},
    {"genre_id": 8, "movie_id": 16},
    {"genre_id": 15, "movie_id": 16},
)
